// ABOUTME: Shared runner for "agent A vs agent B" h2h sweeps using BAL-2 incremental commits + per-sweep markdown report.
// ABOUTME: Used by the overnight-2 orchestrator's Track A/B sweeps to avoid 8x copy-pasted boilerplate.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { GamePool } from "./pool";
import { roundRobinParallel, type NamedAgentSpec } from "./run-parallel";
import { defaultConfig, type RuleConfig } from "../engine/config";
import { elapsedS } from "./format";
import { appendResultAndCommit, commitFileAndPush } from "./incremental-results";
import { workerCount } from "./worker-count";

export interface H2HConfig {
  /** Label appearing in report headlines + commit messages, e.g. "lookahead2-vs-heuristic-c-2p". */
  label: string;
  /** baseSeed for the sweep — distinct per script so reruns are deterministic + non-overlapping. */
  baseSeed: bigint;
  /** Players in each game (round-robin schedule alternates seats fairly). */
  nPlayers: number;
  /** Total games run for THIS h2h. roundRobin distributes them across seat pairings. */
  gamesPerMatchup: number;
  /** TurnCap for the games. */
  turnCap: number;
  /** Variant config (variant (c) is the common case; override for other variants). */
  config: RuleConfig;
  /** The two agents in the matchup. */
  agents: [NamedAgentSpec, NamedAgentSpec];
  /** Output paths. Dirs are created as needed. */
  jsonlPath: string;
  markdownPath: string;
}

export async function runH2H(opts: H2HConfig): Promise<void> {
  const t0 = Date.now();
  const workers = workerCount();
  const pool = new GamePool(workers);
  console.log(`=== ${opts.label} (baseSeed ${opts.baseSeed}, ${workers} workers, nPlayers=${opts.nPlayers}, games=${opts.gamesPerMatchup}) ===`);
  console.log(`Agents: ${opts.agents[0].name} vs ${opts.agents[1].name}`);
  const cfg = opts.config;
  console.log(`Config: bs=${cfg.boardSize} r=${cfg.radius} iron=${cfg.ironCount} vt=${cfg.victoryThreshold} noIronRequiresPerimeter=${cfg.noIronRequiresPerimeter}`);

  try {
    const rr = await roundRobinParallel(
      opts.agents,
      {
        playerCounts: [opts.nPlayers],
        gamesPerMatchup: opts.gamesPerMatchup,
        seed: opts.baseSeed,
        config: opts.config,
        turnCap: opts.turnCap,
        onGame: (done, total, _pc, r) => {
          const w = r.winnerOrCoalition.length === 0 ? "none" : r.winnerOrCoalition.join("+");
          const summary = `${opts.label} t=${r.turns} ${r.victoryType} w=${w}`;
          if (done % 10 === 0 || done === total || done === 1) {
            console.log(`  [${opts.label} ${done}/${total}] ${summary} (${elapsedS(t0)})`);
          }
          appendResultAndCommit(opts.jsonlPath, {
            data: {
              done, total,
              nPlayers: opts.nPlayers,
              turns: r.turns,
              victoryType: r.victoryType,
              winner: r.winnerOrCoalition,
              hitTurnCap: r.hitTurnCap,
              elapsedSec: (Date.now() - t0) / 1000,
            },
            meta: { label: opts.label, done, total, summary },
          });
        },
      },
      pool,
    );

    const aName = opts.agents[0].name;
    const bName = opts.agents[1].name;
    const aWinRate = rr.winRates[aName] ?? 0;
    const bWinRate = rr.winRates[bName] ?? 0;
    const aVsBDirect = rr.headToHead[aName]?.[bName] ?? 0;
    const bVsADirect = rr.headToHead[bName]?.[aName] ?? 0;
    const decisive = aVsBDirect + bVsADirect;
    const draws = opts.gamesPerMatchup - decisive;

    const lines: string[] = [];
    lines.push(`# ${opts.label}`);
    lines.push(``);
    lines.push(`**Date:** 2026-05-28/29 overnight queue.`);
    lines.push(``);
    lines.push(`**Config:** boardSize=${cfg.boardSize}, radius=${cfg.radius}, ironCount=${cfg.ironCount}, victoryThreshold=${cfg.victoryThreshold}, noIronRequiresPerimeter=${cfg.noIronRequiresPerimeter}, alliancesEnabled=${cfg.alliancesEnabled}.`);
    lines.push(`**Methodology:** ${opts.gamesPerMatchup} ${opts.nPlayers}P games, ${aName} vs ${bName}, round-robin seat schedule, baseSeed ${opts.baseSeed}, turnCap ${opts.turnCap}.`);
    lines.push(``);
    lines.push(`## Results`);
    lines.push(``);
    lines.push(`| Agent | Win rate | Direct wins vs opp | Elo |`);
    lines.push(`| --- | ---: | ---: | ---: |`);
    lines.push(`| ${aName} | ${(aWinRate * 100).toFixed(1)}% | ${aVsBDirect} | ${(rr.elo[aName] ?? 0).toFixed(0)} |`);
    lines.push(`| ${bName} | ${(bWinRate * 100).toFixed(1)}% | ${bVsADirect} | ${(rr.elo[bName] ?? 0).toFixed(0)} |`);
    lines.push(``);
    lines.push(`Decisive: ${decisive} of ${opts.gamesPerMatchup}; draws/ties: ${draws}.`);
    lines.push(``);
    lines.push(`---`);
    lines.push(`*Generated by \`src/sweep/lookahead2-h2h-runner.ts\` (via overnight-2 orchestrator).*`);
    const md = lines.join("\n") + "\n";
    mkdirSync(dirname(opts.markdownPath), { recursive: true });
    writeFileSync(opts.markdownPath, md, "utf8");
    commitFileAndPush(opts.markdownPath, `report: ${resolve(opts.markdownPath).split("/").pop()}`);
    console.log(`\nDone in ${elapsedS(t0)}. Report: ${opts.markdownPath}`);
  } finally {
    pool.close();
  }
}
